allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  electron: true
  esbuild: true
  koffi: true
  node-pty: true
onlyBuiltDependencies:
  - '@deepseek-ai/dsh-subprocess-local'
  - electron
  - esbuild
  - koffi
  - node-pty
